### PR TITLE
feat: label generated code

### PR DESCRIPTION
**Pull request by zcstarr**
small  PR for issue #42 . I believe this is what the request feature was intended to do. It's a bit unclear if you wanted something a bit more involved or a different approach. lmk what you think

### CODE REVIEW

**Comment by BelfordZ** [comment]
@zcstarr Thank you very much for the contrib. Much appreciated.

Looks like we have to sort out CI for forks sooner than I thought!! haha thank you!

Give me a day or so to get CI running against this branch, and then LGTM!

🎉

**Comment by BelfordZ** [comment]
@zcstarr created #102 to track getting it fixed

**Comment by BelfordZ** [comment]
Should be all set now.

Just need you to sign your commit.

**Comment by zcstarr** [comment]
@shanejonas commit signed PTAL when you get a chance, also I signed the contributor license agreement as well, as an fyi. Thanks!

**Comment by shanejonas** [comment]
@zcstarr just need to upload your public key to github to verify it:

image

**Comment by zcstarr** [comment]
@shanejonas thanks I'm finally verified \o/ gpg'd up.

**Pull request merged**
